2024-04-23 20:25:35,324 : INFO : root : Loading config.
2024-04-23 20:25:35,602 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2024-04-23 20:25:35,603 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-23 20:25:35,603 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml.
2024-04-23 20:25:35,652 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml
2024-04-23 20:25:35,653 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/config/config.yaml.
2024-04-23 20:25:35,793 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/config/config.yaml
2024-04-23 20:25:35,795 : INFO : ConfigProcessor : Config file cache created: /tmp/9f2098f750e45235613be58ba15b9646.mpf_cache
2024-04-23 20:25:35,834 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/modes/attract/config/attract.yaml.
2024-04-23 20:25:35,835 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/modes/attract/config/attract.yaml
2024-04-23 20:25:35,835 : INFO : ConfigProcessor : Config file cache created: /tmp/0488c24d6cb11f71168a087186f8afaf.mpf_cache
2024-04-23 20:25:35,836 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/modes/game/config/game.yaml.
2024-04-23 20:25:35,837 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/modes/game/config/game.yaml
2024-04-23 20:25:35,837 : INFO : ConfigProcessor : Config file cache created: /tmp/7559345efe69122f4d6fb5f65214b482.mpf_cache
2024-04-23 20:25:35,837 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/modes/base/config/base.yaml.
2024-04-23 20:25:35,885 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/modes/base/config/base.yaml
2024-04-23 20:25:35,886 : INFO : ConfigProcessor : Config file cache created: /tmp/ea6b25128768fa7bfd9e42011d34475f.mpf_cache
2024-04-23 20:25:35,887 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/modes/bonus/config/bonus.yaml.
2024-04-23 20:25:35,888 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/modes/bonus/config/bonus.yaml
2024-04-23 20:25:35,888 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/modes/bonus/config/bonus.yaml.
2024-04-23 20:25:35,900 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/modes/bonus/config/bonus.yaml
2024-04-23 20:25:35,901 : INFO : ConfigProcessor : Config file cache created: /tmp/fecad1d527faf1d03547df1920e5db10.mpf_cache
2024-04-23 20:25:35,901 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/shows/./triple_pulse_show.yaml.
2024-04-23 20:25:35,904 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/shows/./triple_pulse_show.yaml
2024-04-23 20:25:35,904 : INFO : ConfigProcessor : Config file cache created: /tmp/fcc4c9d209c9a032c06d4f66ec129faa.mpf_cache
2024-04-23 20:25:35,904 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/shows/./attract_show.yaml.
2024-04-23 20:25:35,917 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/shows/./attract_show.yaml
2024-04-23 20:25:35,917 : INFO : ConfigProcessor : Config file cache created: /tmp/1589a8837fa04fabe2b0cb060c0683ab.mpf_cache
2024-04-23 20:25:35,917 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2024-04-23 20:25:35,917 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-23-20-25-35-mpf-futurama.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-23 20:25:35,917 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2024-04-23 20:25:35,918 : INFO : Machine : Machine path: /home/mpfuser/pinball/Futurama31
2024-04-23 20:25:35,918 : INFO : Machine : Platform: linux
2024-04-23 20:25:35,918 : INFO : Machine : Python executable location: /usr/bin/python3
2024-04-23 20:25:35,918 : INFO : Machine : Python version: 3.7.3 (64-bit)
2024-04-23 20:25:35,918 : INFO : Machine : Initialise MPF.
2024-04-23 20:25:35,960 : INFO : P-Roc : Connecting to P-ROC
2024-04-23 20:25:36,218 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 14. Hardware Board ID: 1
2024-04-23 20:25:36,253 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2024-04-23 20:25:36,253 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 14, 'prev_value': None, 'change': True}
2024-04-23 20:25:36,253 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2024-04-23 20:25:36,254 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,290 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.9, 'prev_value': None, 'change': True}
2024-04-23 20:25:36,290 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 3376, 'prev_value': None, 'change': True}
2024-04-23 20:25:36,290 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,290 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,290 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.3', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-4.19.0-20-amd64-x86_64-with-debian-10.12', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '4.19.0-20-amd64', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#1 SMP Debian 4.19.235-1 (2022-03-17)', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-04-23 20:25:36,291 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-04-23 20:25:36,319 : INFO : EventManager : Event: ======'drop_target_bank_crew_bank_up'====== Args={}
2024-04-23 20:25:36,349 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at /usr/local/lib/python3.7/dist-packages/mpf/core/system_wide_device.py:15> exception=ConfigFileError('Configuration error in bd_left_post ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True"')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 364, in _configure_targets
    self._validate_config()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 311, in _validate_config
    '"mechanical_eject: True"'.format(self.name), 4)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_post: Configuration error in bd_left_post ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-4.html)
2024-04-23 20:25:36,353 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<SystemWideDevice.device_added_system_wide() done, defined at /usr/local/lib/python3.7/dist-packages/mpf/core/system_wide_device.py:15> exception=ConfigFileError('Configuration error in bd_right_post ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True"')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 364, in _configure_targets
    self._validate_config()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 311, in _validate_config
    '"mechanical_eject: True"'.format(self.name), 4)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_right_post: Configuration error in bd_right_post ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-4.html)
2024-04-23 20:25:36,354 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-04-23 20:25:36,354 : INFO : Machine : Starting the main run loop.
2024-04-23 20:25:36,354 : INFO : Machine : Shutting down...
2024-04-23 20:25:36,355 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-23 20:25:36,370 : INFO : SwitchController : Found active switch: (30, <Platform.P3-ROC>) <switch.s_trough1>
2024-04-23 20:25:36,371 : INFO : SwitchController : Found active switch: (28, <Platform.P3-ROC>) <switch.s_pe_platter>
2024-04-23 20:25:36,371 : INFO : SwitchController : Found active switch: (23, <Platform.P3-ROC>) <switch.s_dt_nibbler>
2024-04-23 20:25:36,441 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 364, in _configure_targets
    self._validate_config()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 311, in _validate_config
    '"mechanical_eject: True"'.format(self.name), 4)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_post: Configuration error in bd_left_post ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-4.html)
